---
title: "Moral Foundations Questionnaire 2.0, Research Question 2"
output: html_document
---

```{r include = F}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(ggpubr)
library(lsa)
library(purrr)

```

```{r include = F}

# load data
df <- read_csv("human_mfq_responses.csv")

names(df)[names(df) == "Response"] <- "human_response"

names(df)[names(df) == "Item"] <- "item"

# unique ID for each participant
df$participant <- paste0(df$Participant, "_", df$Group)

# remove group column
df <- subset(df, select = -c(Group, Participant))

# add language and persona manipulation levels
# (because separate similarity measure for each human compared to each LLM in each condition)

# language
df <- bind_rows(
  df %>% mutate(language = "English"),
  df %>% mutate(language = "Chinese")
)

# persona 
df <- bind_rows(
  df %>% mutate(persona = "China"),
  df %>% mutate(persona = "USA")
)
## LLM ratings
llm <- read_csv("llm_mfq_responses.csv",
                col_select = c("LLM", "language", "persona", "item", "llm_response"))

# merge human responses with LLM responses
df <- left_join(df, llm)

# z-score
df <- df %>%
  group_by(participant) %>%
  mutate(
    human_z = as.numeric(scale(human_response))
  ) %>%
  ungroup() %>%
  group_by(LLM, language) %>%
  mutate(
    llm_z = as.numeric(scale(llm_response))
  ) %>%
  ungroup()

# remove straight liners
df <- filter(df, !is.na(human_z))

```

```{r echo = F}

# ensure vectors are ordered the same for each participant, LLM
df <- arrange(df, participant, LLM, language, persona, item)

df <- df %>%
  group_by(participant, LLM, language, persona) %>%
  summarise(
    cosine = as.numeric(cosine(llm_z, human_z))[1],
    human_nation = ifelse(str_sub(first(participant), -3, -1) == "ina", "China", "USA"),
    .groups = 'drop'
  ) %>%
  ungroup()
  
write_csv(df, "mfq_cosine_rq2.csv")

```

# Cosine similarity as a function of congruence with participant nationality

```{r include = F}

info <- read_csv("llm_info.csv")

df <- left_join(df, info)

df$nation_language <- ifelse(df$language == "English", "USA", "China")

# sum coding congruence with participant nationality
df$cong_GroupLang <- ifelse(df$nation_language == df$human_nation, 0.5, -0.5)
df$cong_GroupLang <- df$cong_GroupLang - mean(df$cong_GroupLang)

df$cong_GroupID   <- ifelse(df$persona == df$human_nation, 0.5, -0.5)
df$cong_GroupID <- df$cong_GroupID - mean(df$cong_GroupID)

df$cong_GroupOrigin <- ifelse(df$llm_nation == df$human_nation, 0.5, -0.5)
df$cong_GroupOrigin <- df$cong_GroupOrigin - mean(df$cong_GroupOrigin)

```

## Descriptive stats

```{r echo = F}

df %>%
  group_by(cong_GroupLang, cong_GroupID, cong_GroupOrigin) %>%
  summarise(
    Mean = mean(cosine),
    SD = sd(cosine)
  ) %>%
  rename(
    `Language congruence` = cong_GroupLang,
    `Persona congruence` = cong_GroupID,
    `Country of origin congruence` = cong_GroupOrigin
  )

```

## Linear regression

### (for all factors, congruent with participant nationality = 0.5, incongruent = -0.5)

```{r echo = F}

summary(lm(
  cosine ~ cong_GroupLang * cong_GroupID * cong_GroupOrigin,
  df))

```

# Figure 3: similarity as a function of congruence

```{r echo = F}

df$Condition <- paste0(df$language, ", ", df$persona)

df$Condition <- factor(df$Condition, levels = c(
  "English, USA", "English, China", "Chinese, USA", "Chinese, China"
))

ggplot(df,
       aes(y = cosine, x = llm_nation, colour = human_nation, fill = Condition)) +
  geom_boxplot(outliers = F) +
  theme_minimal(base_size = 14) +
  labs(colour = "Participant nationality", 
       fill = "Language, persona") +
  scale_fill_manual(
    values = c("white", "lightgrey", "darkgrey", "black")
  ) +
  xlab("LLM country of origin") +
  ylab("Cosine similarity to humans\nMoral Foundations Questionnaire 2.0")

```

```{r echo = F}

ggplot(df, aes(
  y = cosine, 
  colour = as.factor(cong_GroupID), 
  fill = as.factor(cong_GroupLang), 
  x = as.factor(cong_GroupOrigin))) +
  geom_boxplot(outliers = F) +
  scale_fill_manual(
    values = c("lightgrey", "darkgrey"), 
    labels = c("Incongruent", "Congruent")
  ) +
  scale_colour_manual(
    values = c("gold3", "#800080"),
    labels = c("Incongruent", "Congruent")
  ) +
  scale_x_discrete(
    labels = c("Incongruent", "Congruent")
  ) +
  labs(y = "Cosine similarity to humans on MFQ-2\nby congruence with nationality", 
       colour = "Persona", 
       x = "LLM origin", 
       fill = "Language") +
  theme_minimal(base_size = 14)

```
